language:
    node_js
node_js:
    - 'node'
install:
    - npm ci
    - npm install -g codecov
script:
    - npm run build && npm run lint:manifest
    - npm run coverage && codecov
cache:
    directories:
        - "$HOME/.npm"
