language:
    node_js
node_js:
    - 'node'
sudo: false
cache:
    directories:
        - "$HOME/.npm"

jobs:
    include:
        - stage: test
            install:
                - npm ci
                - npm install -g codecov
            script:
                - npm run ext:build:chrome && npm run lint
                - npm run test
            after_success:
                - codecov
        - stage: deploy
            # if: branch = master
            script:
                - EXTENSION_ID=${EXTENSION_ID} CLIENT_SECRET=${CLIENT_SECRET} CLIENT_ID=${CLIENT_ID} REFRESH_TOKEN=${REFRESH_TOKEN} node ./deploy.js
